### ISSUE TITLE
roles doesn't say anything

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/MinnBot#6]
Locally, bot knows who people are, can set their roles, etc. But in Heroku it doesn't print anything.

```
2015-06-19T20:38:36.887519+00:00 app[web.1]: Incoming message received
2015-06-19T20:38:36.889327+00:00 app[web.1]: [Fri Jun 19 2015 20:38:36 GMT+0000 (UTC)] ERROR Unable to call the listener: TypeError: Cannot call method 'toLowerCase' of undefined
2015-06-19T20:38:36.889330+00:00 app[web.1]: TypeError: Cannot call method 'toLowerCase' of undefined
2015-06-19T20:38:36.889331+00:00 app[web.1]:   at Brain.usersForRawFuzzyName (/app/node_modules/hubot/src/brain.coffee:135:7, <js>:123:23)
2015-06-19T20:38:36.889333+00:00 app[web.1]:   at Brain.usersForFuzzyName (/app/node_modules/hubot/src/brain.coffee:144:20, <js>:132:27)
2015-06-19T20:38:36.889336+00:00 app[web.1]:   at TextListener.Listener.call (/app/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
2015-06-19T20:38:36.889334+00:00 app[web.1]:   at TextListener.callback (/app/scripts/roles.coffee:52:17, <js>:56:31)
2015-06-19T20:38:36.889337+00:00 app[web.1]:   at Robot.receive (/app/node_modules/hubot/src/robot.coffee:163:9, <js>:112:33)
2015-06-19T20:38:36.889339+00:00 app[web.1]:   at Slack.Adapter.receive (/app/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
2015-06-19T20:38:36.889340+00:00 app[web.1]:   at Slack.run.self.robot.name (/app/node_modules/hubot-slack/src/slack.coffee:147:26, <js>:141:16)
2015-06-19T20:38:36.889342+00:00 app[web.1]:   at callbacks (/app/node_modules/hubot/node_modules/express/lib/router/index.js:161:37)
2015-06-19T20:38:36.889343+00:00 app[web.1]:   at param (/app/node_modules/hubot/node_modules/express/lib/router/index.js:135:11)
2015-06-19T20:38:36.889346+00:00 app[web.1]:   at Router._dispatch (/app/node_modules/hubot/node_modules/express/lib/router/index.js:170:5)
2015-06-19T20:38:36.889347+00:00 app[web.1]:   at Object.router (/app/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
2015-06-19T20:38:36.889345+00:00 app[web.1]:   at pass (/app/node_modules/hubot/node_modules/express/lib/router/index.js:142:5)
2015-06-19T20:38:36.889349+00:00 app[web.1]:   at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:190:15)
2015-06-19T20:38:36.889350+00:00 app[web.1]:   at multipart (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
2015-06-19T20:38:36.889352+00:00 app[web.1]:   at module.exports (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9)
2015-06-19T20:38:36.889353+00:00 app[web.1]:   at IncomingMessage.module.exports (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
2015-06-19T20:38:36.889355+00:00 app[web.1]:   at IncomingMessage.EventEmitter.emit (events.js:93:17)
2015-06-19T20:38:36.889357+00:00 app[web.1]:   at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2015-06-19T20:38:36.889356+00:00 app[web.1]:   at IncomingMessage._emitEnd (http.js:367:10)
2015-06-19T20:38:36.889359+00:00 app[web.1]:   at Socket.socket.ondata (http.js:1832:22)
2015-06-19T20:38:36.889360+00:00 app[web.1]:   at TCP.onread (net.js:404:27)
```

**Comment by jonathanstegall** [comment]
duplicate with #15

**Comment by jonathanstegall** [comment]
we think this was a problem with slack's hubot adapter. maybe it fixed when we updated a while back.
